// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkokYd4do321P6eLZgkS2r9hg_GWZqWzU',
    appId: '1:163844566466:web:b78fa0efbdfeb44c6e3a5b',
    messagingSenderId: '163844566466',
    projectId: 'programacionmovil-c6576',
    authDomain: 'programacionmovil-c6576.firebaseapp.com',
    storageBucket: 'programacionmovil-c6576.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3qo3w3kSvEV43OSZ7R3qTBJvrZ4Q4a4U',
    appId: '1:163844566466:android:daded0203bf2fe666e3a5b',
    messagingSenderId: '163844566466',
    projectId: 'programacionmovil-c6576',
    storageBucket: 'programacionmovil-c6576.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaY1KhtRj1Ptot0e66SJkzVeyKzVjGYnE',
    appId: '1:163844566466:ios:bb89a583a30ac14e6e3a5b',
    messagingSenderId: '163844566466',
    projectId: 'programacionmovil-c6576',
    storageBucket: 'programacionmovil-c6576.firebasestorage.app',
    iosBundleId: 'com.example.pmsn2025',
  );
}
